# Generated by Django 3.1.7 on 2021-11-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_auto_20211116_0706"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="addressee",
            new_name="adressee",
        ),
    ]
